### ISSUE TITLE
Create a Dialog Fragment

### ISSUE THREAD

**Issue by swatisingh0960** [codepathgroup5/wanttoknow#15]

**Comment by kristianss27** [comment]
The dialog fragments was created and you can see it once the user has a PersonalList created, the floatting button on the listView allows the user open this Dialog Fragment with the Questionary Flow on it

**Comment by kristianss27** [comment]
The dialog fragments was created and you can see it once the user has a PersonalList created, the floatting button on the listView allows the user open this Dialog Fragment with the Questionary Flow on it

**Comment by kristianss27** [comment]
The dialog fragments was created and you can see it once the user has a PersonalList created, the floatting button on the listView allows the user open this Dialog Fragment with the Questionary Flow on it
